declare module 'veryfi-lens-wasm'
declare module 'veryfi-lens-wasm/veryfi-lens'
declare module 'veryfi-lens-wasm/device-uuid'
declare module 'veryfi-lens-wasm/fingerprint-id'
declare module 'veryfi-lens-wasm/lens-wasm'
declare module 'veryfi-lens-wasm/opencv'
declare module 'veryfi-lens-wasm/feature-detect'